# NumPy
[(**Num**eric **Py**thon)](http://www.numpy.org/)

## Содержание
 - Особенности Numpy
 - Некоторые функции
 - Массивы ndarray и операции с ними
 - Cпособы создания массива
 - Индексация
 - Операции с матрицами и векторами
 - Полезные функций и методы
 - Вычисление статистик

## Где мы уже работали с Numpy сами того не подозревая?

[Инструкция](https://colab.research.google.com/notebooks/io.ipynb) по загрузке данных в colab

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
df = pd.read_csv('/content/sample_data/california_housing_test.csv')  # path/to/coins.csv
df.head()

longitude  latitude  ...  median_income  median_house_value
0    -122.05     37.37  ...         6.6085            344700.0
1    -118.30     34.26  ...         3.5990            176500.0
2    -117.81     33.78  ...         5.7934            270500.0
3    -118.36     33.82  ...         6.1359            330000.0
4    -119.67     36.33  ...         2.9375             81700.0

[5 rows x 9 columns]

In [ ]:
df.values

array([[-1.22050e+02,  3.73700e+01,  2.70000e+01, ...,  6.06000e+02,
         6.60850e+00,  3.44700e+05],
       [-1.18300e+02,  3.42600e+01,  4.30000e+01, ...,  2.77000e+02,
         3.59900e+00,  1.76500e+05],
       [-1.17810e+02,  3.37800e+01,  2.70000e+01, ...,  4.95000e+02,
         5.79340e+00,  2.70500e+05],
       ...,
       [-1.19700e+02,  3.63000e+01,  1.00000e+01, ...,  2.20000e+02,
         2.28950e+00,  6.20000e+04],
       [-1.17120e+02,  3.41000e+01,  4.00000e+01, ...,  1.40000e+01,
         3.27080e+00,  1.62500e+05],
       [-1.19630e+02,  3.44200e+01,  4.20000e+01, ...,  2.60000e+02,
         8.56080e+00,  5.00001e+05]])

In [ ]:
type(df.values)

numpy.ndarray

### Структуры данных Series и DataFrame в Pandas - это надстройки над массивами Numpy!

# <a id="Особенности Numpy"><span style="color:green">Особенности</span></a>

**NumPy** - это open-source модуль для Python, который предоставляет общие математические и числовые операции в виде пре-скомпилированных, быстрых функций (использует типы из C, которые существенно быстрее чем Python типы). Они обеспечивают функционал, который можно сравнить с функционалом MatLab.  

Возможности:
   - поддержка многомерных массивов (включая матрицы);
   - поддержка высокоуровневых математических функций, предназначенных для работы с многомерными массивами.  

**Типы данных в NumPy**

В `Python` к числовым типам относятся:
   - int
   - float
   - bool
   - complex   
   
В `numpy` имеются эти типы, а также обёртки над этими типами, которые **используют реализацию типов на C**, например, `int8`, `int16`, `int32`, `int64` (подробнее о типах данных `numpy` можно прочитать [здесь](https://www.numpy.org/devdocs/user/basics.types.html)). За счёт того, что используются типы данных из C, numpy получает ускорение операций.

In [ ]:
import numpy as np
from tqdm import tqdm_notebook  # посмотрите, что делает tqdm_notebook

# <a id="Некоторые функции"><span style="color:green">Некоторые функции</span></a>

В numpy реализовано огромное число функций.
Вот некоторые из них:

In [ ]:
import math
dir(math)

- np.log(x) - натуральный логарифм x
- np.log10(x) - десятичный логарифм x
- np.log2(x)
- np.sqrt(x) - квадратный корень из x
- np.power(x, n) - возведение x в степень n
- np.abs(x) - модуль x
- np.round(x, n) - математическое округление x
- np.floor(x) - округление вниз
- np.ceil(x) - округление вверх
- np.int(x) - округление к нулю
- sin(x) - синус
- cos(x) - косинус
- ... и т. д..

**Примеры**

Все аргументы, описание функций легко найти:

In [ ]:
# справка
np.log?

Также используйте сочетаия клавиш `Shift + Tab` для получения короткой справки (Работает только в Jupyter Notebook)

In [ ]:
np.log(10, dtype=np.float64)

2.302585092994046

In [ ]:
np.log(0.)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

In [ ]:
0 == 0.

True

In [ ]:
type(np.inf)

float

In [ ]:
1.

1.0

In [ ]:
print(np.log10(10))
print(np.log10(100))

1.0
2.0


In [ ]:
np.round(4.5), np.floor(4.5), np.ceil(4.5), np.int(4.5)

(4.0, 4.0, 5.0, 4)

In [ ]:
np.round(3.5), np.floor(3.5), np.ceil(3.5), np.int(3.5)

(4.0, 3.0, 4.0, 3)

In [ ]:
np.round(-4.5), np.floor(-4.5), np.ceil(-4.5), np.int(-4.5)

(-4.0, -5.0, -4.0, -4)

In [ ]:
pow(2, 3)

8

In [ ]:
np.power?

In [ ]:
# переполнение!
np.power(2, 1000), type(np.power(2, 1000))

(0, numpy.int64)

In [ ]:
np.power(2, 2, dtype=np.int8), type(np.power(2, 2, dtype=np.int8))

(4, numpy.int8)

То же самое но с помощью Python-типа int

In [ ]:
2 ** 1000, type(2 ** 1000) # питоновское возведение в степень

(10715086071862673209484250490600018105614048117055336074437503883703510511249361224931983788156958581275946729175531468251871452856923140435984577574698574803934567774824230985421074605062371141877954182153046474983581941267398767559165543946077062914571196477686542167660429831652624386837205668069376,
 int)

In [ ]:
sum(int(digit) for digit in str(2 ** 1000)), len(str(2 ** 1000))

(1366, 302)

In [ ]:
np.cos(np.pi)

-1.0

In [ ]:
np.e

2.718281828459045

# <a id="Массивы ndarray и операции с ними"><span style="color:green">Массивы ndarray и операции с ними</span></a>

Основным объектом `NumPy` является *однородный* многомерный массив, в numpy он реализован через объект `ndarray`. Массивы (`ndarray`) похожи на списки (`list`), но могут хранить только элементы одного типа. Производить вычисления с массивами гораздо быстрее и эффективнее чем со списками.

Наиболее важные атрибуты объектов ndarray:
1. **`ndarray.ndim`** - число измерений (чаще их называют "оси") массива.
  
2. **`ndarray.shape`** - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.
3. **`ndarray.size`** - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.
4. **`ndarray.dtype`** - объект, описывающий тип элементов массива. Можно определить dtype, используя стандартные типы данных Python. Можно хранить и numpy типы, например: bool, int16, int32, int64, float16, float32, float64, complex64
5. **`ndarray.itemsize`** - размер каждого элемента массива в байтах.
6. **`ndarray.data`** - буфер, содержащий фактические элементы массива. Обычно не нужно использовать этот атрибут, так как обращаться к элементам массива проще всего с помощью индексов.

Одномерный массив

In [ ]:
# создание массива из списка
a = np.array([1, 2, 3, 1, 0])
type(a)

numpy.ndarray

In [ ]:
type(1+0j)

In [ ]:
np.array?

In [ ]:
print(a)
print("a.shape = ", a.shape)
print("a.ndim =", a.ndim)
print("a.size =", a.size)
print("a.dtype =", a.dtype)
print("Размер каждого элемента массива в байтах a.itemsize =", a.itemsize)
print("Обращение к элементу a[0] =", a[0])

Двумерный массив

In [ ]:
b = np.array([[1, 8, 3], 
              [3, 2, 1], 
              [3, 5, 6]])

In [ ]:
print(b)
print("a.shape = ", b.shape)
print("a.ndim =", b.ndim)
print("a.size =", b.size)
print("a.dtype =", b.dtype)
print("Размер каждого элемента массива в байтах a.itemsize =", b.itemsize)
print("Нулевая строка b[0] =", b[0])
print("Обращение к элементу b[строка][столбец]: b[0][1] =", b[0][1])
print("Обращение к элементу b[строка, столбец]: b[0, 1] =", b[0, 1])

[[1 8 3]
 [3 2 1]
 [3 5 6]]
a.shape =  (3, 3)
a.ndim = 2
a.size = 9
a.dtype = int64
Размер каждого элемента массива в байтах a.itemsize = 8
Нулевая строка b[0] = [1 8 3]
Обращение к элементу b[строка][столбец]: b[0][1] = 8
Обращение к элементу b[строка, столбец]: b[0, 1] = 8


In [ ]:
[[1, 8, 3], 
              [3, 2, 1], 
              [3, 5, 6]]

In [ ]:
import sys
sys.getsizeof(10 ** 1_000_000_0)

In [ ]:
sys.getsizeof?

In [ ]:
sys.getsizeof(list(range(100000)))

In [ ]:
sys.getsizeof(np.array(list(range(100000)), dtype=np.int16))

In [ ]:
np.array(list(range(100000)), dtype=np.int16).nbytes

Индексация n-мерных массивов такая же как и для n-мерных списоков.

## <a id="Cпособы создания массива"><span style="color:green">Cпособы создания массива</span></a>

- Из списка

In [ ]:
# из списка
m = np.array([[1, 8, 3], 
              [3, 2, 1], 
              [3, 5, 6]])
print(m)

- Создание единичной матрицы

In [ ]:
# создание единичной матрицы
m = np.eye(3, dtype=np.int8)
print(m)

In [ ]:
# m = np.eye(N=3, M=4) 
m = np.eye(3, 4)  # аналог первой строчки
# m = np.eye(M=4, N=3)  # аналог первой строчки
print(m)

In [ ]:
np.eye?

- Создание матрицы из единиц

In [ ]:
np.ones?

In [ ]:
# создание матрицы из единиц
# m = np.ones(5, 4) # ошибка 
# m = np.ones((5, 4))
m = np.ones([5, 4])
print(m)
print(type(m[1]))

In [ ]:
m = np.ones(5)
print(m)
print(m.shape)
print(type(m[1]))

- Создание матрицы из нулей

In [ ]:
# создание матрицы из нулей
m = np.zeros((4, 1))
print(m)
print(m.shape)
print(m.ndim)

In [ ]:
# создание вектора из нулей
v = np.zeros(4)
print(v)

- **Создание массива из диапазона**

   - создание массива из диапазона значений [start, end)

In [ ]:
# np.arrange(start=0, stop, step=1)
m = np.arange(0, 10, 2)
print(m)
m = np.arange(10)
print(m)

[0 2 4 6 8]
[0 1 2 3 4 5 6 7 8 9]


<span style="color:blue">Создайте матрицу 5x5 со значениями строк в диапазоне от 0 до 4</span>

In [ ]:
m = np.zeros((5, 5))
print(m)
m

In [ ]:
np.arange(5)

In [ ]:
m = np.zeros((5, 5))
m += np.arange(5)  # m = m + np.arange(5)
print(m)

In [ ]:
sample_m = list([0 for x in range(5)] for _ in range(5))
print(*sample_m, sep='\n')

In [ ]:
sample_m += list(range(5))
sample_m

- создание массива из диапазона значений [start, stop] с заданием кол-ва точек

In [ ]:
m = np.linspace(0, 3, 4)
print(m)

In [ ]:
np.linspace?

In [ ]:
np.linspace(0, 3)

In [ ]:
np.linspace(0)

- создание массива из диапазона [$base^{start}$, $base^{end}$]

In [ ]:
# np.logspace(start, end, num=50, base=10)
m = np.logspace(2.0, 5.0, num=4, base=2.0)
print(m)

- **Создание массива из случайных чисел**

In [ ]:
np.random.seed(42)
print(np.random.rand(2, 2))

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


In [ ]:
np.random.seed(42)
print(np.random.rand(2, 2))

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


В `numpy` есть аналог модуля `random` - `numpy.random`. Используя типизацию из C, он как и свой аналог генерирует случайные данные.

In [ ]:
# массив чисел из равномерного (uniform) распределения в диапазоне [0, 1)
# np.random.rand(d0, d1, d2, ...) d0, d1,... - pазмеры возвращаемого массива
print(np.random.rand(2, 2))
print(np.random.rand(2, 2).shape)

[[0.31062938 0.65663127]
 [0.74874275 0.61060213]]
(2, 2)


In [ ]:
np.random.rand?

In [ ]:
# массив чисел из стандартного нормального (norm) распределения
# нормальное распределение в заданном shape
np.random.randn(2, 3, 2)

array([[[-0.23415337, -0.23413696],
        [ 1.57921282,  0.76743473],
        [-0.46947439,  0.54256004]],

       [[-0.46341769, -0.46572975],
        [ 0.24196227, -1.91328024],
        [-1.72491783, -0.56228753]]])

In [ ]:
# массив из случайно выбранных чисел
# size - размер возвращаемого массива, reaplce=False без замещения
np.random.choice(a=np.arange(20), size=10, replace=True)

array([ 9, 15, 14, 14, 18, 11, 19,  2,  4, 18])

In [ ]:
np.random.choice?

In [ ]:
np.random.choice(a=np.arange(20), size=(5, 5), replace=False)

ValueError: ignored

**А что со временем?**

In [ ]:
import numpy as np

In [ ]:
%%time
a = list(range(10 ** 8))
#  %%time - выводит время выполнения ячейки

In [ ]:
%time a_numpy = np.arange(10 ** 8)

In [ ]:
type(a_numpy)

In [ ]:
%%time
for idx, elem in enumerate(a):
    a[idx] = elem * 2

In [ ]:
%%time
b = np.arange(1, 10 ** 8 + 1, dtype=np.float64)
b *= 2

In [ ]:
a = list(range(10))
a * 2

**Вывод:** старайтесь использовать векторизированные вычисления!

## <a id="Индексация"> <span style="color:green">Индексация</span></a>

In [ ]:
m = np.array([[1, 8, 3], 
              [3, 2, 1], 
              [3, 5, 6]])
print(m)

[[1 8 3]
 [3 2 1]
 [3 5 6]]


In [ ]:
# третья строка (вторая если считать с 0)
m[2]

In [ ]:
# третья строка (вторая если считать с 0)
m[2, :]  # list: m[2][:]

In [ ]:
# второй столбец
m[:, 1]

In [ ]:
# как было со списками
a[:]

In [ ]:
a = [[i for i in range(10)] for i in range(5)]
a

In [ ]:
a[:][1]

In [ ]:
a_np = np.array(a)
a_np

In [ ]:
a_np[::2, 2:7:2]

Выделение "подматрицы"

In [ ]:
m

array([[1, 8, 3],
       [3, 2, 1],
       [3, 5, 6]])

In [ ]:
# возьмем только нулевую и вторую строки в 0 столбце
# m [список строк, список столбцов]
m[[0, 2], [0]]

array([1, 3])

In [ ]:
m[[0, 2], [0, 1, 2]]

IndexError: ignored

In [ ]:
m[(np.array([0, 2]), np.array([0, 1, 2]))]

IndexError: ignored

In [ ]:
m

array([[1, 8, 3],
       [3, 2, 1],
       [3, 5, 6]])

In [ ]:
np.ix_([0, 2], [0, 2])

(array([[0],
        [2]]), array([[0, 2]]))

In [ ]:
m_dop = m[np.ix_([0, 2], [0, 1, 2, 1])]

In [ ]:
m_dop

array([[1, 8, 3, 8],
       [3, 5, 6, 5]])

## <a id="Операции с матрицами и векторами"><span style="color:green">Операции с матрицами и векторами</span></a>

В NumPy двумерный массив можно рассматривать и как матрицу, то есть для него определены все матричные операции. Одномерный массив также можно рассматривать как вектор.

**Транспонирование**

Транспонированной матрицей $A^{T}$ называется матрица, полученная из исходной матрицы $A$ путем замены строк на столбцы.

In [ ]:
m = np.array([[1, 12, 3, 4], 
              [3, 2, 10, 2], 
              [3, 56, 6, 11]])
print(m)
print()
print(m.T)

**Скалярное произведение векторов**

Рассмотрим два вектора $a$ и $b$ в n-мерном пространстве  
$a = (a_1, a_2, a_3, \dots a_n)$   
$b = (b_1, b_2, b_3, \dots b_n)$   
Скалярное произведение векторов $a$ и $b$ определяется следующим образом:  
$$\langle a, b \rangle = a_1 b_1 + a_2 b_2 + a_3 b_3 \dots + a_n b_n = \sum_{i = 1}^{n} a_i b_i$$

In [ ]:
a = np.array([3, 1, 5, 2])
b = np.array([2, 5, 2, 4])
# <a, b> = 3*1 + 1*5 + 5*2 + 2*4
print(a @ b)    # python 3 style
print(a.dot(b)) 
print(np.dot(a, b))

In [ ]:
a

**Умножение матриц**  
  
Операция умножения определена для двух матриц, таких что число столбцов первой равно числу строк второй. 

Пусть матрицы $A$ и $B$ таковы, что $A \in \mathbb{R}^{n \times k}$ и $B \in \mathbb{R}^{k \times m}$.    
__Произведением__ матриц $A$ и $B$ называется матрица $C$, такая что 
$$c_{ij} = \sum_{r=1}^{k} a_{ir}b_{rj}$$, 
где  $c_{ij}$ — элемент матрицы $C$, стоящий на пересечении строки с номером $i$ и столбца с номером $j$.

In [ ]:
a = np.array([[1, 2], [0, 1]])
b = np.array([[4, 1], [2, 2]])
print(a @ b)    # python 3 style
print(a.dot(b)) 
print(np.dot(a, b))

[[8 5]
 [2 2]]
[[8 5]
 [2 2]]
[[8 5]
 [2 2]]


Также доступно *ПОКООРДИНАТНОЕ* умножение, не путать с матричным!

In [ ]:
print(a * b)

[[4 2]
 [0 2]]


In [ ]:
[0, 1] @ [0, 1]

TypeError: ignored

**Умножение матриц и векторов**

In [ ]:
m = np.array([[1, 2], [0, 1], [2, 4]])
print(m)
v = np.array([2, 5])
print("v = ", v)

[[1 2]
 [0 1]
 [2 4]]
v =  [2 5]


In [ ]:
m @ v

array([12,  5, 24])

In [ ]:
m = np.array([[1, 2, 1, 1], [0, 1, 1, 1], [2, 4, 1, 1]])
print(m)
v = np.array([2, 5])
print("v = ", v)
m @ v

[[1 2 1 1]
 [0 1 1 1]
 [2 4 1 1]]
v =  [2 5]


ValueError: ignored

#### Broadcasting (Расширение/адаптация размерностей)
Мощный механизм, позволяющий NumPy работать с массивами различной формы при выполнении арифметических операций. Часто у нас есть меньший массив и больший массив, и мы хотим использовать меньший массив несколько раз, чтобы выполнить некоторую операцию над большим массивом

[Наглядный туториал](https://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc)

In [ ]:
# прибавление вектора ко всем строкам матрицы

In [ ]:
# без broadcasting
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([3, 4, 5])
# empty like создает пустую матрицу такого же размера как x
y = np.empty_like(x) # создаем пустую структуру, в нее мы будем складывать ответ

print(x)
print(v)
print(f'y: \n{y}')

for i in range(4):
  y[i, :] = x[i, :] + v

print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[3 4 5]
y: 
[[93883010890464              0              0]
 [             0              0              0]
 [             0              0              0]
 [             0              0              0]]
[[ 4  6  8]
 [ 7  9 11]
 [10 12 14]
 [13 15 17]]


In [ ]:
%%time
a = np.zeros((1000, 1000))

In [ ]:
%%time
np.empty_like((10000, 10000))

`np.tile` повторяет массив v (n,m,...) n раз по 0-ой оси и m раз по 1-ой итд, получается новый массив

In [ ]:
v

array([3, 4, 5])

In [ ]:
vv = np.tile(v, (4, 2))
vv # получилась матрица такой же размерности как и матрица x

array([[3, 4, 5, 3, 4, 5],
       [3, 4, 5, 3, 4, 5],
       [3, 4, 5, 3, 4, 5],
       [3, 4, 5, 3, 4, 5]])

[Гиперкуб](https://ru.wikipedia.org/wiki/%D0%93%D0%B8%D0%BF%D0%B5%D1%80%D0%BA%D1%83%D0%B1)

In [ ]:
x

In [ ]:
y = x + vv
print(y)

In [ ]:
v

In [ ]:
x + v

Бродкастинг двух массивов работает следующим образом:
*   Если массивы не имеют одинаковый ранг (кол-во размерностей), нужно выровнять кол-во размерностей, добавлением дополнительных "единичных" размерностей массиву меньшего ранга
*   Говорят, что два массива *совместимы* в i-ой размерности, если они имеют одинаковый по величине набор значений в этой размерности, или если один из массивов имеет ровно 1 элемент в этом измерении.
*   Массивы **broadcastable**, если они совместимы во всех размерностях.
*   После адаптации каждый массив ведет себя так, как будто он имеет форму, равную поэлементному максимуму форм двух входных массивов.
*   В любом измерении, где один массив имел размер 1, а другой массив имел размер больше 1, первый массив ведет себя так, как если бы он был скопирован "вдоль" этого измерения

Прибавим теперь не по строкам, а по столбцам

In [ ]:
v

In [ ]:
x

Для этого нужно добавить "дополнительную" размерность 1.

Обратите внимание, что (4,) и (4,1) это разные numpy массивы по форме. Первое интерпретируется как строка матрицы, а второе как столбец. Проведите над этим утверждением пару минут.

In [ ]:
np.arange(1, 5)

In [ ]:
np.arange(1, 5).reshape(4, 1)

In [ ]:
np.arange(1, 5).reshape(4, 1).reshape(4, 1, 1) 

In [ ]:
np.arange(1,5).reshape(4, 1).shape

In [ ]:
x

In [ ]:
x + np.arange(1, 5)

In [ ]:
x + np.arange(1,5).reshape(4, 1) # у нас происходит сложение по столбцам

## <a id="Полезные функции и методы"><span style="color:green">Полезные функции и методы</span></a>

Все функции описанные в предыдущем разделе можно применять к массивам!

In [ ]:
b = np.array([[1, 2],
              [10, 100]])
b

array([[  1,   2],
       [ 10, 100]])

In [ ]:
np.log(b)

array([[0.        , 0.69314718],
       [2.30258509, 4.60517019]])

In [ ]:
np.log(b).shape == b.shape

True

In [ ]:
np.sin(b)

Кроме математических функций есть также полезные функции для работы с массивами.

In [ ]:
a = np.random.choice(a=np.linspace(1, 50, 50) + 100, size=10, replace=False)
print(a)

[145. 124. 136. 111. 135. 125. 118. 104. 106. 123.]


- Замена элементов по индексу

In [ ]:
np.put(a, ind=[0, 2], v=[-44, -55, -66])
a

- Выделение элементов по условию

In [ ]:
np.where(a < 0, -42, a)

In [ ]:
np.where(a < 0, -42)

In [ ]:
np.where(a < 0)

In [ ]:
a < 0

In [ ]:
a[np.where(~(a < 0))]

In [ ]:
~(a < 0)

- Сортировка

In [ ]:
a[a < 0]

In [ ]:
a

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

In [ ]:
np.sort(a, kind='merge_sort')

Индексы сортированного массива

In [ ]:
np.argsort(a)

array([7, 8, 3, 6, 9, 1, 5, 4, 2, 0])

In [ ]:
# создание матрицы для демонстрации примеров
m = np.round(np.random.rand(4, 5) * 10, 3)
print(m)

In [ ]:
# сортировка по столбцам
np.sort(m, axis=0)

In [ ]:
# сортировка по строкам
np.sort(m, axis=1)

<span style="color:blue">Отсортируйте все столбцы по первому столбцу:</span>

In [ ]:
np.random.seed(42)
a = np.random.randint(0, 10, (5, 3))
print(a)
print()
print(a[a[:, 1].argsort()])

[[6 3 7]
 [4 6 9]
 [2 6 7]
 [4 3 7]
 [7 2 5]]

[[7 2 5]
 [6 3 7]
 [4 3 7]
 [4 6 9]
 [2 6 7]]


In [ ]:
a[:, 1].argsort()

array([4, 0, 3, 1, 2])

In [ ]:
print(a[np.array([4, 0, 3, 1, 2])])

In [ ]:
m = np.zeros((3, 4, 5))
m += np.arange(5)
print(m)
np.sum(m, axis=-1)

In [ ]:
a = np.arange(8).reshape(8, 1, 6, 1)
print(a.shape)
b = np.arange(35).reshape(7, 1, 5)
print(b.shape)
(a + b).shape

In [ ]:
a = np.arange(48).reshape(8, 1, 6, 1, 1, 1, 1)
print(a.shape)
b = np.arange(35).reshape(7, 1, 5)
print(b.shape)
(a + b).shape

- **newaxis**

Добавление нового измерения

In [ ]:
a = np.linspace(1, 10, 10)
print(a)
print(a.shape)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
(10,)


In [ ]:
print(a[np.newaxis, :, np.newaxis])
print("New shape ", a[np.newaxis, :, np.newaxis].shape)

[[[ 1.]
  [ 2.]
  [ 3.]
  [ 4.]
  [ 5.]
  [ 6.]
  [ 7.]
  [ 8.]
  [ 9.]
  [10.]]]
New shape  (1, 10, 1)


In [ ]:
print(a[None, :])
print("New shape ", a[np.newaxis, :].shape)

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]]
New shape  (1, 10)


In [ ]:
m = np.random.randint(0, 10, (5, 10))
m

array([[4, 1, 7, 5, 1, 4, 0, 9, 5, 8],
       [0, 9, 2, 6, 3, 8, 2, 4, 2, 6],
       [4, 8, 6, 1, 3, 8, 1, 9, 8, 9],
       [4, 1, 3, 6, 7, 2, 0, 3, 1, 7],
       [3, 1, 5, 5, 9, 3, 5, 1, 9, 1]])

In [ ]:
m.reshape(2, 1, -1)

array([[[4, 1, 7, 5, 1, 4, 0, 9, 5, 8, 0, 9, 2, 6, 3, 8, 2, 4, 2, 6, 4,
         8, 6, 1, 3]],

       [[8, 1, 9, 8, 9, 4, 1, 3, 6, 7, 2, 0, 3, 1, 7, 3, 1, 5, 5, 9, 3,
         5, 1, 9, 1]]])

In [ ]:
a.shape

In [ ]:
a[np.newaxis, :].reshape(-1, 1, 1)

In [ ]:
m, a

In [ ]:
m @ a

In [ ]:
b = a[:, np.newaxis]

In [ ]:
(m @ b).shape

In [ ]:
m @ a[:, np.newaxis]

In [ ]:
m @ a[np.newaxis, :]

In [ ]:
a.shape, a[np.newaxis, :].shape

In [ ]:
m1, m2 = np.ones((4, 3, 6)), np.zeros((2, 3))
m1, m2

In [ ]:
m.reshape(-1, *m2.T.shape)

In [ ]:
np.ones((10,))

In [ ]:
np.arange(5).reshape(5, 1)

In [ ]:
np.tile(np.arange(2), (5, 2))

In [ ]:
np.tile(np.arange(4).reshape(2, 2), (5, 2))

In [ ]:
a

In [ ]:
m = a.reshape((5, 2, 1, 1))
print(m)
print(m.shape)
print('------------------------')
print(m[..., np.newaxis, np.newaxis].shape)
print('------------------------')
# print(m[:, np.newaxis, np.newaxis])
print("New shape ", m[:, np.newaxis, np.newaxis].shape)

- **any all**

`Any` возвращает True, если хотя бы один элемент `True`   
`All` возвращает True, если все элементы `True`

In [ ]:
any([True, True, False, True, False, False, False])

In [ ]:
all([True, True, False, True, False, False, False])

In [ ]:
np.array([1, 1, 0, 2]) == np.array([1, 1, 0, 2])

In [ ]:
# сравнение векторов
all(np.array([1, 1, 0, 2]) == np.array([1, 1, 0, 2]))

In [ ]:
all(np.array([1, 1, 0, 0]) == np.array([1, 1, 0, 2]))

In [ ]:
any(np.array([1, 1, 0, 0]) == np.array([1, 1, 0, 2]))

- Методы all и any

In [ ]:
np.array([1, 1, 0, 8, 1, 5, 1, 1]) == np.array([1, 1, 3, 2, 1, 5, 1, 1])

In [ ]:
a = (np.array([1, 1, 0, 8, 1, 5, 1, 1]) == np.array([1, 1, 3, 2, 1, 5, 1, 1])).reshape((2, 4))
print(a)

In [ ]:
# any по строкам
a.any(axis=1)

In [ ]:
# any по столбцам
a.any(axis=0)

In [ ]:
# По строкам и столбцам
a.all((0, 1)) # берем элементы по осям исходной подматрицы с индексами 0 и 1

In [ ]:
a.all?

- diff   
out[n] = a[n+1] - a[n]

In [ ]:
a = np.array([1, 2, 4, 7, 0])
print(a)
print(np.diff(a))

- split (забиение на части)

In [ ]:
a = np.arange(10)
print(a)

In [ ]:
np.split(a, [2, 7]) # разбивает по элементам 2 и 7

## <a id="Вычисление статистик"><span style="color:green">Вычисление статистик</span></a>

In [ ]:
a = np.random.randint(-10, 70, (5, 4))
print(a)

[[-4 10 62 28]
 [ 7 -7 49  3]
 [-2 42 -9 49]
 [60 33 -3 36]
 [24 67 25 39]]


- среднее

In [ ]:
a.mean()

In [ ]:
# среднее по столбцам
a.mean(axis=0)

In [ ]:
# среднее по строкам
a.mean(axis=1)

- медиана

In [ ]:
print(np.median(a))
print(np.median(a, axis=0))
print(np.median(a, axis=1))

26.5
[ 7. 33. 25. 36.]
[19.   5.  20.  34.5 32. ]


- максимум и минимум

In [ ]:
print(a)

In [ ]:
print(a.max())              # максимальный элемент
print(a.max(axis=0))        # максимумы по столбцам
print(a.argmax(axis=0))     # индексы строк максимумов по столбцам
print(a.max(axis=1))        # максимумы по строкам
print(a.argmax(axis=1))     # индексы столбцов максимумов по строкам

- счетчик

In [ ]:
np.bincount(np.arange(5))
# np.arange(5) == array([0, 1, 2, 3, 4])
# [0, 1, 2, 3, 4]

In [ ]:
np.bincount(np.array([0, 1, 1, 3, 2, 1, 7]))
# [0, 1, 2, 3, 4, 5, 6, 7]

Как это получилось? Получили массив соответсвующий диапазону от 0 до max. И посчитали кол-во попаданий в 0, 1, 2, ... max.

In [ ]:
# с помощью аргумента weights можно посчитать сумму части эелемента массива
sub_sums = np.bincount(np.array([2, 0, 2, 1, 0, 0, 2, 2, 0, 1]), 
                        weights=[4, 4, 2, 3, 5, 1, 6, 1, 7, 5])
# [0, 1, 2]
# 0 -> 4 + 5 + 1 + 7 = 17
# 1 -> 3 + 5 = 8
# 2 -> 4 + 2 + 6 + 1 = 13
print(sub_sums)

<span style="color:blue">Как найти наиболее частое значение в массиве?</span>

In [ ]:
z = np.random.randint(0, 10, 50)
print(z)
print(np.bincount(z).argmax())

[5 0 5 6 9 5 5 0 6 1 0 1 8 4 5 0 1 4 4 0 4 6 5 7 8 5 0 2 7 8 9 3 7 9 8 2 2
 5 0 1 7 7 3 4 8 8 1 0 6 4]
0


In [ ]:
np.bincount(z)

In [ ]:
# Задачи

Создайте массив из 100 элементов (от 1 до 100), переформатируйте в формат (10 * 10), сделайте слайсинг с шагом 2 по каждой оси.

In [ ]:
z = np.random.randint(0, 100, 100) 
z

array([27,  4, 53,  0, 90, 60, 89,  0, 17,  0,  6, 30, 34, 55, 23, 43, 96,
       85,  9, 22, 83, 99, 75, 35, 88, 57, 40, 58, 90, 30, 20, 41, 78, 49,
       75, 85, 95, 92, 15, 71,  7,  7, 93, 23, 12, 44, 44, 16, 27, 66, 25,
       56, 29, 56, 81, 84, 12, 92, 87, 86, 76, 24, 52, 79, 87, 31, 56, 26,
       22,  3, 63, 67, 68, 26, 54, 92, 65, 90, 34, 35, 11, 21, 43,  8, 19,
       41,  4,  8, 14, 59, 94, 85, 18, 21, 90, 85, 94, 95, 34, 80])

In [ ]:
arr = np.arange(1, 101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
arr = np.arange(1, 101, 1).reshape((10, 10))
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [ ]:
arr = np.arange(1, 101, 1).reshape((10, 10))[::2, ::2] 
arr

array([[ 1,  3,  5,  7,  9],
       [21, 23, 25, 27, 29],
       [41, 43, 45, 47, 49],
       [61, 63, 65, 67, 69],
       [81, 83, 85, 87, 89]])